server:
  port: 8084

spring:
  datasource:
    url: jdbc:mysql://localhost:3308/msreservation?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect