server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3309/msaccesscontrol?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  rabbitmq:
    host: localhost
    port: 5672
    username: myuser
    password: secret

# URLs dos microserviços
msvisitor:
  url: http://localhost:8082
msresident:
  url: http://localhost:8081