# MSAccessControl/src/main/resources/application.yml
server:
  port: 8082

spring:
  cache:
    type: redis  # Habilita cache
  data:
    redis:
      host: localhost
      port: 6379

  # Se usar banco de dados:
  datasource:
    url: jdbc:mysql://localhost:3306/access_db
    username: root
    password: senha123