version: '3.8'
services:
  db-visitor:
    image: mysql:8.0
    container_name: msvisitor-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: msvisitor
    ports:
      - "3307:3306"
    command: --default-authentication-plugin=mysql_native_password 
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql