version: '3.8'
services:
  db-accesscontrol:
    image: mysql:8.0
    container_name: msaccesscontrol-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: msaccesscontrol
    ports:
      - "3309:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

  rabbitmq:
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_PASS=secret
      - RABBITMQ_DEFAULT_USER=myuser
    ports:
      - "5672:5672" 